services:
  spring-boot:
    image: spring-boot:latest

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"

    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=car_rental_db
      - DB_USERNAME=root
      - DB_PASSWORD=12345

    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: "no"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: car_rental_db
volumes:
  mysql_data: